### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by martianmartian** [ravenscroftj/SPE#2]
Can you please tell us how to install it?

**Comment by fenderrex** [comment]
I just made a pull request to the readme.md or look for my fork if I make one
just open **init**.py and it will lunch no install.
**init**.py just imports SPE.py what ever is in the root of the file is ran so if you make a python program >>>import SPE 
SPE opens and your program will wait till SPE is closed and may even terminate the rest for your script...

**Comment by fenderrex** [comment]
Pull request was accepted issue closed?

**Comment by ravenscroftj** [comment]
yup all good :)
